- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-to-pypi
    check:
      jobs:
        - build-openstack-sphinx-docs:
            voting: false
        - requirements-check:
            voting: false
