#
# Copyright (c) 2011, 2012 OpenStack LLC.
# Copyright (c) 2012, 2013 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import os
import subprocess

VERBOSE = os.environ.get('VERBOSE', False)


class CommandException(Exception):
    pass


# following function is taken from git-review
def run_command(cmd, status=False, env={}):
    if VERBOSE:
        print(datetime.datetime.now(), "Running:", cmd)
    newenv = os.environ
    newenv.update(env)
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT, env=newenv)
    (out, nothing) = p.communicate()
    if p.returncode:
        raise CommandException
    out = out.decode('utf-8')
    if status:
        return (p.returncode, out.strip())
    return out.strip()


def git_describe_version():
    try:
        v = run_command(['git', 'describe', '--tags', '--dirty'])
    except CommandException:
        raise

    return v


def hpgit_version():
    try:
        from ghp import hpgit_version
    except ImportError:
        raise
    return hpgit_version.version


def write_version_file():
    try:
        v = git_describe_version()
    except:
        return
    print __name__
    with open(os.path.join(os.path.dirname(__file__),
                           "hpgit_version.py"), 'w') as f:
        f.write("# Autogenerated file, do not edit by hand")
        f.write("version = %s" % v)


def get_version():
    for vfunc in hpgit_version, git_describe_version:
        try:
            return vfunc()
        except:
            pass

    return 'unknown-version'


version = get_version()
